apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc-runner
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: arc-runners
  releaseName: ownrunners
  chart:
    spec:
      chart: gha-runner-scale-set
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: arc-values
