apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 10m
  targetNamespace: falco
  releaseName: falco
  chart:
    spec:
      chart: falco
      version: "v7.0.2"
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: falco-values
