apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco
resources:
  - falco.yml

configMapGenerator:
  - name: falco-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
