apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: websocket-dc

resources:
  - ns.yml
  - secret.yml
  - deployment.yml
  - ingress.yml
