---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: websocket-dc-env
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: websocket-dc-env
  data:
    - secretKey: ORIGINS
      remoteRef:
        key: websocket-dc-websocket-dc-env
