---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: websocket-dc-env
  namespace: websocket-dc
spec:
  encryptedData:
    ORIGINS: AgAodmJ5NQQPFg+VCTO33A7QW3SMj8dWqezHXjrq/c/ytNxzZAvt6zMokqEZNRiLe76JdTWO1Nm+81wQRWXyDulPt644GqieTrprEq+rPbF1bjytGMe6eJ4KHW4Kt0TfXvQIWdlJNu58w1ljcVBk8Q1CcNwERzLSe6zTF3e/amTiGM/4CVp2gN4r12r6mrno0Aa9vcUEZWR63/qaAeBZ9ck1mmBUlYPj/GVg63L2jjCXyrgQcipMr4K2Zc6YJs6bnQkJ1lcztdcC9MEAU5SpIZ3fA7GJPhAZF7+/jiUjwv/2eULBKk/dVOJwwKSd6E5ZDTZnXhHta6kIyv8PeLCPhImLnj1/wMG+Z+heIM7wc1R6wf5TQgisOmMUQU+ub5txex9Vlo0vAOMgMur07lK/6Zb5UmHBO1p5k+eRtny17U+T1ROZQlp/lCi+Zjswwgcu4oubKZLeg7A7CQTGNtYD0oEyFsbJuB9NPJiKlowTC/ksazYHv1fBrJvWEg4XkrpQtrvDTypXeyXhyT8XeXHZXsEOeO1aTppYBc8DKRFLURIvtUZPjcewwmHiIntOQFrAa6M0mWNcQRLeA7i0BRn50UjP45Xsoa1JM7elOF2BX69WsaDu/jz8RW2eTh8V5YcM1pCf9XehcEtagizM9T9mbE58OONRgWcSpTkXsOlOlhqQl0N+ImXRmPQml/yxmqHkb2q2Wek0KRrCE786fpXw53akC/POxxzs6VMEEiStEmwLQlvb/EJxrVRoXmJPaeaNEYz9FXR8UqS+EbKqf0XXr7S+Juhs/Ru/WzR014JhdAjf2Wl+Wrx9eo5hI8d3H1fCChN4iTqUw3vXJs85rH+tNF6K8MjmK1CozvbDbaLYXSnolchqD9Uj15313kjcRyN/6PCc+SYhtxLt9TWivev3fKwUjhYHn30=
  template:
    metadata:
      creationTimestamp: null
      name: websocket-dc-env
      namespace: websocket-dc
