apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - longhorn.yaml
  - route.yml

configMapGenerator:
  - name: longhorn-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
