apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: longhorn-system
  releaseName: longhorn
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      version: "1.9.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-values
