apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
spec:
  dnsNames:
    - registry.kvlk.hu
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: registry-tls
  usages:
    - digital signature
    - key encipherment
