---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: diun
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./apps/diun
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: diun
  timeout: 3m0s
  wait: true
