---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: github
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./apps/github-runner
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: actions-runner-system
  timeout: 3m0s
  wait: true
