---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kuma
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./apps/uptime-kuma
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kuma
  timeout: 3m0s
  wait: true
