apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero

resources:
  - secret.yaml
  - velero.yaml

configMapGenerator:
  - name: velero-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
