---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: aws-secret
  data:
    - secretKey: cloud
      remoteRef:
        key: velero-aws-secret
