---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: velero
spec:
  encryptedData:
    cloud: AgAMLRVWfqRadRBtBkSPsbSGCa1zdrjNaQFYTBwIO3AlYNQpunwlcxXVM2+fwHepb9xNE4j80Tt/d6vLXUE1krwUn6IZYTbY1iYKRZ9QZe2Fked5TcFJ0QOClQzpzwCVphtXp/GIvoJrrMTqrZkGCxDCzoqJYXF/fsrSHu0FrCL5kH0Zr316E9ImJjowC5RLB71Y6CYwmSFJsLU1AfH/To6JNqKP0J2fGLBTLApjghzmkTAavJqx2FJBNG+XyE4XJw2l6upnvrPjh3gktBEusE1tN3hlMTveYIbTEmzpXEIIz5T1AqRLqd1uxUnpZGnNe3t/4aQ+PCZx0nGfA6Tolch/uzgvPKt39kpVLFwNJmwnyTeVub9wjoXQctY7lmCoit+IpW2DlMFxYzoCUW6uKb2gXA9bVHmMOaY4GNCAQY2vcflIjt4CIF3eP5z2WcJIRtG9rUz67Tds8969EaUQyO/sapvWGLj+EBNieAZ0o+JKb1XI5e38bRfLVsVivQGp8H7YXo4gRW2hQz8awhKczLHMjNTry7uom6fwp0cSfxU+V+sU/4jnsqBL1Uj8joa+gPgx1lSH2hVYCm9Hna1Zi9l3vRko9jt3aY7b9qYrf15fyDVg4SXpL22cWgYdg3YWqUKDts4XM1N84zUhzq+HninsOpNy/V/SceucqyoHF1xu1iufSVb+PKNX0G+jPUj4DBkSEQPYIw1C3oukv1PH2o+UqJzr56oxUmh77TgsXwi0Xx907mZWy5GSztTJZQvOJawd43vbiQ3hl5/Cc0YW3zuzgPW7W380ZMJcXUWVFvLqLmfLLuclRr54t31vsCy3MlOixoCICkkn+/wB8g//ZWN9ihDBrw==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: velero
    type: Opaque
