configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: tojglibackup
      config:
        region: eu-central-1
  volumeSnapshotLocation:
    - name: default
      provider: aws

credentials:
  existingSecret: aws-secret

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.0
    volumeMounts:
      - mountPath: /target
        name: plugins

kubectl:
  image:
    repository: bitnamilegacy/kubectl
    tag: 1.33.4
