apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: velero
  releaseName: velero
  chart:
    spec:
      chart: velero
      reconcileStrategy: ChartVersion
      version: v11.2.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: velero-values
