---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: zot
spec:
  encryptedData:
    admin-pw: AgBMv+3HeHttQO9gNzTj8SGfzWL2lCPxnFgb2/YRRRyzkf9gqpQmQeOY4k6IKyruYAqm93XRsO5PrK9Es6+U716yKldFUonQ5b40WoDUs/yRAihh7w9MOzkH8qyjmzg1P6aLl9jFh8Y54nOoFa1PcFPEtrqt+wgTR1iwS3sUZiTZ2lg3W7XuKOgXFcXDA5hlGl3ySEnA9TiVHH2+ouTreA8/CPuOGFn87JWXbk/x+oY2HwU5zzF1hzEcGqiecwo8dHVdY5z70NXA2+XdIn7v/bG+kMMbfPUOuJmQFeiOpTuC2zLVSkOp61sAzpkAP4doxi74/Rrqk3pPJSdYeca4yUT8/5OgWbleyLrg0Qm3jil0ywqFjxB3vxOouK5K8iQ550X8zXLljK0OlIEPIbT7dr7q8zluT8mu1qk7q8ZRK9yIggvAAq6McHpKYVloGeM4BhuNhYtkKbVtEpO1mUw6xd3RjPnQPJEf2dg5QNn7DTYfd4Hibk0o7igeSrAx8eFS3UKLhZ9tjQ0UGe0qBNWbsSNMWF/z0tEmdOh3p89x5bFDMlnFD1Fj6FKfvsqVpqmQyXtKJhz8sixghgUOpT49BkKsb0my+M+uonFU5v0+yLVNOz9Ofe8aZ6Gk0i/OkdaT2w17BTdHUXmD4/DgaWlOSgX2w+hsBqxgpHtBzs4ZYOBUXi8/emEJ6+jXgzuiYz+WVRX4hIKYX0WowwA6T2Ma3dxSkRMOVhgL8ZB6z21nszwsERo8UfwE5pmVDDrKwATf+ubOyHdgX8Ynwc2gRwN0S4BHZYqK
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: zot
    type: Opaque
