---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: htpasswd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: htpasswd
  data:
    - secretKey: htpasswd
      remoteRef:
        key: zot-htpasswd
