apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-systems
resources:
  - runnercontroller.yaml

configMapGenerator:
  - name: arc-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
