---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-user
  namespace: n8n
spec:
  encryptedData:
    password: AgBJhG5bKI8/lDgTgDZjL6cUrJYPASu52gccvnduRHBmW+WpyF//Jbd8WGogfvegL/5AN6a30q8FWWal966j/460AR8GtwcIXIFnk0S9vqvkAIuGr0ui/MGJ3yTQEksRv6IWnJZga7kWK0y0iLGLn/pZDl5T1FZ18cWPoNJoibUYd2PXchiVOqQIe+cdMWP4x5RhRUm+FMwFjJoGTQUfmxqf0hF1TuZRz0Lg9jq9n59AdtoAmP42dDFMla7VJdy3LmncT0UfGJNDxMcgi917f082kSYq5KDuj+kwOQGpw6hyF0hkugRd4YlS+dmZkfgfUGxvOe+g7/6k8iT+NO+Xcv3A2HGfOFvmzWylWruPKtB9mbVVaFto1dLbPH93ZJJw8Jof182N7NsERL6iMshewNi8T2dzSmVBz01QkQizvXDqN6u83D9Q+ET6IXhEaDHhqMxrNF29/pLX47MvtoMlwbBMHLsP/HJdKhM9NXluVRb8zaoXuryzmj4m1cb0/P3bHlL1zfzQ51NohfJj4jH+Z4reA1qcmQywCg4oYa6SpQxkv07OW11+1yN+jitWyKqpSQIf25O8fMKbonAXrRDVI8gRjrKzGviZZmZlTLLELs9Ls+dWvbb2qO+75agTHFYQj5CQqZbhTbvFP5EvUD1zfju8jXA4+SZDC5K7+tYcEwRPIolDiBbaX+GyFT8lfLOKAXKDNOr36pnf0JtfrCv2j+k+fcao1w==
    username: AgBzZfAJpFT/rQfuRgmX7xyza0Jfqd0t8AJpOiK56ybkZH+3bgp88HIDhK3N5vEPgli8GCeK11BljfeGpEKDCydPf5pzPCzstB4gWIHfMcCcsX1PrumCO6nAwu9LgWjzfl0W8xYyayCCSwHAjgvLveCFk04Ge8dulOEolUKfd8X+BiKgOvcEpgzdWoj0i7iC+Yvkor8vbisSzDInH3YyxpXfFxTZTEhzjadzr6d9T9HU8e5FsSKlEeWYiv61ahRN+L0zQCo5AxPygNI38OVIRBJ8weNivL6TSBAYf3iu05zXswJ+AgmBi8+sTT3WqZ2B8Yt0hvqwrQICOTdSZs0PpNhbGS7hs4XrQMV5qZEGZuv6LwhDJ10KmUtYPqMHfFbCFSZNUKPlzRNXx2a/Pq7ahWWeATEhBdCQ9TIMJ/BFtWvHA/9mw3o5XF1088P47YBiaJCmOhnenOD/vHYNMef5i5PCwxINMlX6S8CKmqL2GEmZ4PhhY1Rt8spPK1CxiArAViZgk4Wgi3upiQXCMIX3qb/l46z36MOJWcxS5Rk4rjtAtuqjxAsNLFV+h6BbZ00AwS9QO75fmo/dp5s9bRFu6z9OcpvRuiH7bOKikS4MaFGP7CVkWqfepmoUGqaok2DARl23FJCk5lGVLOkzKfDGib5JNMgwM09fIWCerXplDflkUJZVCGnFtoHf2rnHnaKBKU+OwPY=
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-user
      namespace: n8n
