---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mssql-secret
  namespace: default
spec:
  encryptedData:
    MSSQL_SA_PASSWORD: AgA3x7yHSZX4JmOURxIjMu3y8ABp6TPVAUk+5wy3S7RWh0t1Bg8kqMIL45FEA/9TnY46Q23+MjTTx3Gil04i8RlmdwyjjZidC5HjzGQPvgXto0bbjt3d++iLwfmTFLlIu0DDyVTPXnT9xKT72U7Noh3wDg7L88zxfz14sW83eb86h0aR3xVAumCW8EMYmGxCTs3WnLZfQ1uAE/6c2MWO34+btlfHQmmIcr/lMAXhautniGvowL5a3a2Xh937eL0+rRMHcfYE+FgKNoFi8G3NOgGYOmviM+lcRrnSVpKE+CVz2n03UzUl7EspybgXyROeP006k1xNG88qhmnYESn66IaoAG+P8nnpzeHuN1wGZgNOg6bYZbpr3gNAE5BZ57NfIVnR5CqwNu5ysyED2UW7K4O+eJu+93OM0fc81iYxim7e6DLVOQDTUMzaBIYMcjjUCDbedeIvewaiQnwEtwjFiZ3odA7arKJlcERLagbectgwEqOXZq5J9J8vY1ktO+nOYgx6LDMOMYVCKms3HghKxIcqEglqtXU2ORpXncRhRth9DFQ0kQM9ZGdwsNiBkeaJFwdnB6KZ6zlxVx779aBy6KgyALa400uliIlaNqpi2eqURZdBj/vZ3KGtAJOiByzbYHeCZ3tYAxbGwUYqYdX8vDJzsBCPd1q3WTtrq10f5ykwz6dsmK0SPtAU1I1Il3ysL0PaHoYRp90zigg8DgMpZ50=
  template:
    metadata:
      creationTimestamp: null
      name: mssql-secret
      namespace: default
