---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mssql-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mssql-secret
  data:
    - secretKey: MSSQL_SA_PASSWORD
      remoteRef:
        key: default-mssql-secret
