---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: timetagger-env
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: timetagger-env
  data:
    - secretKey: TIMETAGGER_CREDENTIALS
      remoteRef:
        key: timetagger-timetagger-env
