---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: loki-credentials
    template:
      engineVersion: v2
      data:
        USERNAME: "{{ (backticks .raw_json | fromJson).USERNAME }}"
        PASSWORD: "{{ (backticks .raw_json | fromJson).PASSWORD }}"
  data:
    - secretKey: raw_json
      remoteRef:
        key: fluentbit-loki-credentials
