apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: pooler.postgresql.svc
    usernameSecret:
      name: keycloaksecret
      key: dbusername
    passwordSecret:
      name: keycloaksecret
      key: dbpassword
  http:
    httpEnabled: true
    httpPort: 8080
  hostname:
    hostname: https://keycloak.kvlk.hu
    admin: https://keycloak.kvlk.local:8443
    #strict: false
  bootstrapAdmin:
    user:
      secret: keycloaksecret
  ingress:
    enabled: false
  networkPolicy:
    enabled: false
  serviceMonitor:
    enabled: false
  proxy:
    headers: xforwarded
