apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-clients
spec:
  endpointSelector:
    matchLabels:
      app: keycloak
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway-system
      toPorts:
        - ports:
            - port: "123"
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: deny-from-other-namespaces
spec:
  endpointSelector: {} # Applies to all pods in the namespace
  ingress:
    - fromEndpoints:
        - {} # Allow from same namespace (pods without any specific labels)
