---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  name: keycloak
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: keycloak
  hostnames:
    - "keycloak.kvlk.hu"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: keycloak-service
          port: 443
          weight: 1
