---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloaksecret
  namespace: keycloak
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: keycloaksecret
  dataFrom:
    - extract:
        key: keycloak-keycloaksecret
    - extract:
        key: postgresql-keycloak-user
      rewrite:
        - regexp:
            source: "password"
            target: "dbpassword"
        - regexp:
            source: "username"
            target: "dbusername"
