---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dozzle-users
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: dozzle-users
    template:
      engineVersion: v2
      data:
        users.yml: |
          users:
            {{ .username }}:
              password: {{ .password }}
  dataFrom:
    - extract:
        key: dozzle-admin-user
