---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tls
  namespace: envoy-gateway-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cloudflare-tls
    template:
      type: kubernetes.io/tls
  dataFrom:
    - extract:
        key: envoy-gateway-system-cloudflare-tls
        decodingStrategy: Base64
