# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: envoy-gateway
#   namespace: flux-system
# spec:
#   interval: 5m
#   targetNamespace: envoy-gateway-system
#   releaseName: envoy-gateway
#   chart:
#     spec:
#       chart: gateway-helm
#       reconcileStrategy: ChartVersion
#       version: v1.5.1
#       sourceRef:
#         kind: HelmRepository
#         name: envoy
#         namespace: flux-system
