---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eg-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: ClusterIP
      envoyDeployment:
        container:
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
          ports:
            - name: http
              containerPort: 10080
              hostPort: 80
            - name: https
              containerPort: 10443
              hostPort: 443
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eg-internal-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: ClusterIP
      envoyDeployment:
        container:
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
          ports:
            - name: internal
              containerPort: 8443
              hostPort: 8443
