apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-internal
  annotations:
    cert-manager.io/cluster-issuer: "custom-ca-issuer"
spec:
  gatewayClassName: eg
  listeners:
    - name: internal
      hostname: "*.kvlk.local"
      protocol: HTTPS
      port: 9443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: kvlk-local-tls
            kind: Secret
            group: ""
    - name: http
      protocol: HTTP
      port: 9443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
spec:
  parentRefs:
    - name: eg-internal
      sectionName: http
  hostnames:
    - "*.kvlk.local"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
            port: 9443
