apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-internal
  annotations:
    cert-manager.io/cluster-issuer: "custom-ca-issuer"
spec:
  gatewayClassName: eg
  listeners:
    - name: internal
      hostname: "*.kvlk.local"
      protocol: HTTPS
      port: 8443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: kvlk-local-tls
            kind: Secret
            group: ""
    - name: http-redirect
      protocol: HTTP
      port: 8443
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  listeners:
    - name: nextcloud
      hostname: "nextcloud.kvlk.hu"
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: cloudflare-tls
            kind: Secret
            group: ""
    - name: portainer
      hostname: "portainer.kvlk.hu"
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: cloudflare-tls
            kind: Secret
            group: ""
    - name: websocket-dc
      hostname: "websocket-dc.kvlk.hu"
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: cloudflare-tls
            kind: Secret
            group: ""
    - name: registry
      hostname: "registry.kvlk.hu"
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: registry-tls
            kind: Secret
            group: ""
            namespace: registry
    - name: http-redirect
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
spec:
  parentRefs:
    - name: eg
      sectionName: http-redirect
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
