apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-internal
  annotations:
    cert-manager.io/cluster-issuer: "custom-ca-issuer"
spec:
  gatewayClassName: eg
  listeners:
    - name: capacitor
      hostname: capacitor.kvlk.local
      protocol: HTTPS
      port: 9443
      tls:
        mode: Terminate
        certificateRefs:
          - name: capacitor-tls-gateway
            kind: Secret
            group: ""
