---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgAVLE4NBIk59e0ATlKVqHf0tRLgYVq7HMTRPaFEiIl1Euy+gtb2PcsWtjFIOYwdI1esuG4nHkhaxnz/1DOp5JOck6U+vPajYZOknLpgOCJnPRKpIfjwtMmSqTPQvXJoblnbf+cbW6VlEyQhujvP3FBySpYuTfSmMKcCrBzzvcswv5fSAylCyUCgX9xeLeHrUCiQA1ZOl9RiKc0IsW/hE+kF4GxxluaP4jSsgS4RdrZxR6FkhuCAze/LI8Xqywlqb07mSEbW8ZtQhf3/9NFMaXL2SRTpdStM1D8288gLxk3WP1ODxpVaJPYT9j0rH0OS6vpZQnO3XtzRl2fNZ/2Kg9tzopsLIqU8I6dXyZ+UwqjuSovWL6kGDDuhw1GNnqnwuejMyhnwFL9VenaUEgR8wOV5Rf96gDeuaKmz8i1WMJU/I+kGkiE9v4YCwmOq2j2m9ZcFBN7SVQqsSfCw1uIeHTzvQW2XxjLjD+RRbRYzknDrmxT1lUbTo7rLaTR8JJ9k0h3Jmean5xzwxcZNeyNnMZcd03OyB2lnSNZLAgtdqa0awgy9FDFBjVQKswhien5ZIUvzokp33yt7sNmeMnOVfJDnmcIw1R8IpsDBPM0FDv9cV4G0ANZ7fac2wXdy8K+Wle5wg+FB6t7eLJ2asyQNXAO+a9s/hSb4SRVlMyiVOn7G+ShtUNqzGgi8pat5pB/kvWUiYSQl7zR1udiDL+vvCR/5p4qZV4qXqFLTxFFxm6Xq+JTU4gXP12/cwDQnWmO9jgOTef//cAwafAZp9RCKMeTtW3pF92heOe4R3T4WjoZ6Mxp7xIwDnQOO5cmXc60JcmwaubwTEHFjBSuqic7uYMQbBY2BsoG/
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
