apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: kuma

resources:
  - ns.yml

  - service.yml
  - deployment.yml
  - route.yml
  - networkpolicy.yml
