---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-clients
spec:
  endpointSelector:
    matchLabels:
      app: uptime-kuma
  ingress:
    - fromEndpoints:
        - matchLabels:
            gateway.envoyproxy.io/owning-gateway-name: eg-internal
            app.kubernetes.io/name: envoy
            io.kubernetes.pod.namespace: envoy-gateway-system
      toPorts:
        - ports:
            - port: "3001"
              protocol: TCP
          rules:
            http:
              - method: ".*"
                path: ".*"

    - fromEndpoints:
        - matchLabels:
            gateway.envoyproxy.io/owning-gateway-name: eg
            app.kubernetes.io/name: envoy
            io.kubernetes.pod.namespace: envoy-gateway-system
      toPorts:
        - ports:
            - port: "3001"
              protocol: TCP
          rules:
            http:
              # Global
              - method: ".*"
                path: "/icon.svg"
              - method: ".*"
                path: "^/assets/.*"
              # Neoline
              - method: ".*"
                path: "/status/neoline"
              - method: ".*"
                path: "/api/status-page/heartbeat/neoline"
              - method: ".*"
                path: "^/api/neoline/.*"
              - method: ".*"
                path: "^/api/status-page/neoline/.*"
              # KBBudapest
              - method: ".*"
                path: "/status/kbbudapest"
              - method: ".*"
                path: "/api/status-page/heartbeat/kbbudapest"
              - method: ".*"
                path: "^/api/kbbudapest/.*"
              - method: ".*"
                path: "^/api/status-page/kbbudapest/.*"
  egress:
    - toEntities:
        - world
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "443"
        - ports:
            - port: "80"
        - ports:
            - port: "465"
        - ports:
            - port: "41411"
        - ports:
            - port: "8443"
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toCIDRSet:
        - cidr: 10.0.0.161/32
    - toFQDNs:
        - matchName: mortalsoul.23net.hu
      toPorts:
        - ports:
            - port: "2083"
