apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kuma
spec:
  parentRefs:
    - name: eg-internal
      namespace: envoy-gateway-system
      sectionName: internal
  hostnames:
    - "uptime.kvlk.local"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: uptime-kuma-service
          port: 3001
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Referrer-Policy
                value: "no-referrer, strict-origin-when-cross-origin"
              - name: Strict-Transport-Security
                value: "max-age=63072000; includeSubDomains"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-Frame-Options
                value: "SAMEORIGIN"
              - name: X-XSS-Protection
                value: "1; mode=block"
              - name: Permissions-Policy
                value: "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kuma-public
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: uptime
  hostnames:
    - "uptime.kvlk.hu"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: uptime-kuma-service
          port: 3001
          weight: 1
      matches:
        # Global
        - path:
            type: Exact
            value: /icon.svg
        - path:
            type: PathPrefix
            value: /assets
        # Neoline
        - path:
            type: Exact
            value: /status/neoline
        - path:
            type: Exact
            value: /api/status-page/heartbeat/neoline
        - path:
            type: PathPrefix
            value: /api/neoline
        - path:
            type: PathPrefix
            value: /api/status-page/neoline
        # KBBudapest
        - path:
            type: Exact
            value: /status/kbbudapest
        - path:
            type: Exact
            value: /api/status-page/heartbeat/kbbudapest
        - path:
            type: PathPrefix
            value: /api/kbbudapest
        - path:
            type: PathPrefix
            value: /api/status-page/kbbudapest
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Referrer-Policy
                value: "no-referrer, strict-origin-when-cross-origin"
              - name: Strict-Transport-Security
                value: "max-age=63072000; includeSubDomains"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-Frame-Options
                value: "SAMEORIGIN"
              - name: X-XSS-Protection
                value: "1; mode=block"
              - name: Permissions-Policy
                value: "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"
