apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
      template IN A {
        match ^neoline\.kvlk\.local\.$
        answer "{{ .Name }} 60 IN A 10.0.0.161"
        fallthrough
      }

      template IN A {
        match ^.*\.kvlk\.local\.$
        answer "{{ .Name }} 60 IN A 10.0.0.70"
        fallthrough
      }

      log
      errors
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    kvlk.local:53 {
      errors
      cache 30
      template IN A {
        match ^neoline\.kvlk\.local\.$
        answer "{{ .Name }} 60 IN A 10.0.0.161"
      }
      template IN A {
        match ^.*\.kvlk\.local\.$
        answer "{{ .Name }} 60 IN A 10.0.0.70"
      }
      forward . /etc/resolv.conf
    }
