apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
      hosts {
        10.0.0.161 neoline.kvlk.local
        fallthrough
      }
      
      template IN A {
        match ^(.*)\.kvlk\.local\.$
        answer "{{ .Name }} 60 IN A 10.0.0.70"
      }

      forward . 1.1.1.1
      log
      errors
    }
