apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-internal
  namespace: ingress-internal-nginx
spec:
  interval: 5m
  targetNamespace: ingress-internal-nginx
  releaseName: ingress-internal-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: ingress-internal-values
