---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-secret
  namespace: pgadmin
spec:
  encryptedData:
    pgadmin-default-password: AgB76S3DndTjWz21Wxvik8jkYKCJsl0F71oPGcSjjPhmEiYlq26ZbNJIii99V3zPKzbZeodyOUsOwbDDA4TLXZtubOO/OANyqycx9uBQ2t23st+fghI5Se7q5+G3w+mHCT7dACo6cYAKBCsBrT8zfEzzs55H2BtJkFntyxemYVI67g5m5d0KE56XvdSzDYGRNsMDlUmVxTmt9SA5L2qt3oEHZ9zvEiV0qNineNmc1UHSF1dbwJoZ9GlkbxpbX9EJ5U9I26QBAPDumDaPeoufX4pcKaNFW9UGmVb2XBTjP17NVEus+ZunJyENsICHyB6NlbnKlomKaTz1ar2JXxzNVRKgQGVQASL5gtOByTIVKo2Hgj509YOyxqzrtEBhR6zkjXH9wQn9+vA+mRHQWFFl92S7igvaAipUtJ2cu4jB7bWTjIItyEx7JQ2XqPtBSYnFs+q1nXlwy0hHkIMBf8ik0MDWwsNGtTYOS9z+RyraohitcR8u3fbMrpaW3iHbCFcfO+5bje2RtA8aHAi+UxjpPb8BeNqilZkXEIPBftNOpP7Bz5kDhh0GOHRTzbUkrn1zB6B+3scsKYFDLVWGOCIXuAo0cJGp+/zsnW0DpJzBd+mXnbTR7Gc1c7QqP+AzD4/ebscnLr434OYHp3VDTPibr9lYcMpiohvT+4r7Bjy7ubzHj1bGiu8Br+i/aw3Q/Zfg3ovVjFgVix5/wmc35PdTTw==
  template:
    metadata:
      creationTimestamp: null
      name: pgadmin-secret
      namespace: pgadmin
    type: Opaque
