---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: portainer
  namespace: portainer
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - "portainer.kvlk.hu"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: portainer
          port: 9000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
