apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: default
spec:
  instances: 1
  env:
    - name: TZ
      value: Europe/Budapest
  replicationSlots:
    highAvailability:
      enabled: true

  storage:
    size: 10Gi
    storageClass: local-path
  managed:
    roles:
      - name: nextcloud
        ensure: present
        passwordSecret:
          name: nextcloud-user
        comment: NextCloud App
        login: true
        superuser: true
      - name: harbor
        ensure: present
        passwordSecret:
          name: harbor-user
        comment: harbor App
        login: true
        superuser: true
      - name: keycloak
        ensure: present
        passwordSecret:
          name: keycloak-user
        comment: keycloak user
        login: true
        connectionLimit: -1
        inherit: true
  postgresql:
    shared_preload_libraries: ["passwordcheck"]
    parameters:
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "off"
      pgaudit.log_relation: "off"
      pgaudit.log_statement: "off"
