apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-self
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: cnpg-system
    - fromEndpoints:
        - {}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-clients
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/podRole: pooler
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: pgadmin
            io.kubernetes.pod.namespace: pgadmin
        - matchLabels:
            app.kubernetes.io/name: harbor
            io.kubernetes.pod.namespace: harbor
        - matchLabels:
            app: keycloak
            io.kubernetes.pod.namespace: keycloak
      toPorts:
        - ports:
            - port: "5432"
