apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-self
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: postgresql
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-clients
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/podRole: pooler
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: nextcloud
            io.kubernetes.pod.namespace: nextcloud
      toPorts:
        - ports:
            - port: "5432"
    - fromEndpoints:
        - matchLabels:
            app: pgadmin
            io.kubernetes.pod.namespace: pgadmin
      toPorts:
        - ports:
            - port: "5432"
