apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler
spec:
  cluster:
    name: default
  instances: 1
  type: rw
  serviceTemplate:
    metadata:
      labels:
        app: pooler
    spec:
      type: ClusterIP
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "25"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-ro
spec:
  cluster:
    name: default
  instances: 1
  type: ro
  serviceTemplate:
    metadata:
      labels:
        app: pooler
    spec:
      type: ClusterIP
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "25"
