---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: admin-user
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: admin-user
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
    - extract:
        key: postgresql-admin-user
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-user
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: keycloak-user
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
    - extract:
        key: postgresql-keycloak-user
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-user
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: n8n-user
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
    - extract:
        key: postgresql-n8n-user
