apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: cert-manager
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      version: v1.19.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
