---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDWcchuvRTf5LKyythruju3jQOh7gTpYPjjpITBlQ/3w7ct6pC/BaROIxmYQd9i6Wt+4J2PQH5JwVP2QK8DRvBQOG0rg0m8fgukGTayfXk2l1rxNLPdSXHGp39JWwJoXQqQBV0D6IaPDNWpZz54hPoQORJ1FqdbpJ9ZmD6sL5FyJ3ySqHVB/hSdbIo1MkgYK5TG2eVXKSYU1tzzHrkgxCyMhBocKgpkMuCA7sZh32iHMjYsHpJub0MZzXeG7ckieBjsc4gEyBpditbZwl092qeRq7lWDHXiB4iSIUPNsZUYXKGYGyPFA/0VTNbVNsoiwWoQdxHLt1xk0fTG1f+//z8UoKAlw7XTLGFMJmcDbL/m5bO97iHL29+VCgJMO6dB9lrNf9/3S5Y+1MPlB9kf8VXV46WDHi2+N3G5z7NyQ/HCpcC/AUsjf5HfdZFpqa2bkBtFtYlnflAns0RkUWlARZsNGt1PNkTlw8NLSCGlX1Q9Ju4cds4xRsl8I32h0a552t/VrkPNvxSp0xfpmIOPZ7VWuqkZIIbVKm8R7JtSCjXUT1/kuOf1ugUEx/4ZUdLcBzTpYjtuqz4gy+J66kp6YpTrs1di1NfiXUomqWkMts4CJvUdIAA5JdFdzlxO1qiKdj+LOQov0e7YYrlBTKTU/VAzAEOre9dQDRQrtlbQF72slRfT5RS3lwfdTDCJ/LDgmTjlKJuyL6g5PBpKK6tEFrOTqMvWztCJ3M4Rf6vpwDIlWsvJxCpoeCRF
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret-neoline
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC43dcA7025voyAqpR6LvQleMbJ3uF8UwCyRGau8Y+ydkLQxC8Cyj9FZat7M8u3QypfKTcPeyyMwdjOo959lou3vGhnO2KJeJ6Pv/I1rjj3pTjOCGvoIm2jc3gc4i+y0hlnFClwRxfBK6Caxuw72VYkmImui59WUWXYrVj0q+sxU99HP3pr9d6bMNUcOqDDQrPLZCCWWHM57dAHsLzWnL1HnROJnXhQDyJtEruBVxeBJvDTTBXoRu01D/e/oa1NU97l+N+mOWs1FkhZvJEWwImZ4DGIpZCvNeOJ6E6QWp9U39fgPEGcbVJalrTfJUtDdnFYPfqMC+fRzSNr8k47oKAqOTodHkz2i2XGSHLFdoN5GFSlCtjIgfq3QNMmcQ/FHP5CmTGm34VMn7KmSYUhTxxrAjPF1uaH7GhGEoyCYbzft0RiSu5w9uQhQKpzfBmFg0IDMgyC6m5bU0O8JN1PKXNEyO4/3+h2gfvWPUv+ebdsj+NVPqT1Xtxzx+SLbK+qXoHS7WVV6SY/IcERfrEBugeFPaRWk/hktuUXCAhuCm1oEQzKH+ON0XSJ53WRXfgJOCHdy8Ah8Z6GHkoEgegtm4rFvMCccHOKXMCpAbPFzMqvaPXuRnmdXI13NOCELED0cPDQFz7rMloS/wG87ibn5WU0Va0UpegkOhBT8xlX5zLd9q+ZOQnOEOKT8XG/9P6e8MxMa7CPt5+5Rpxzeu/wAHYz5vmMJzUTKEQMHZQ2nN6MxABTkix5ppKN
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret-neoline
      namespace: cert-manager
    type: Opaque
