---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: nextcloud
  hostnames:
    - "nextcloud.kvlk.hu"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: nextcloud
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /

    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/webfinger
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /index.php/.well-known/webfinger

    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/nodeinfo
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /index.php/.well-known/nodeinfo

    - matches:
        - path:
            type: Exact
            value: /.well-known/host-meta
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /public.php?service=host-meta

    - matches:
        - path:
            type: Exact
            value: /robots.txt
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Permissions-Policy
                value: "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"

    # Redirect rules
    - matches:
        - path:
            type: Exact
            value: /.well-known/carddav
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /remote.php/dav
            statusCode: 301

    - matches:
        - path:
            type: Exact
            value: /.well-known/caldav
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /remote.php/dav
            statusCode: 301
