---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: nextcloud
  hostnames:
    - "nextcloud.kvlk.hu"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: nextcloud
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Referrer-Policy
                value: "no-referrer, strict-origin-when-cross-origin"
              - name: Strict-Transport-Security
                value: "max-age=63072000; includeSubDomains"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-Frame-Options
                value: "DENY"
              - name: X-XSS-Protection
                value: "1; mode=block"
              - name: Permissions-Policy
                value: "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"

    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/webfinger
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /index.php/.well-known/webfinger
            statusCode: 301
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Referrer-Policy
                value: "no-referrer, strict-origin-when-cross-origin"
              - name: Strict-Transport-Security
                value: "max-age=63072000; includeSubDomains"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-Frame-Options
                value: "DENY"
              - name: X-XSS-Protection
                value: "1; mode=block"
              - name: Permissions-Policy
                value: "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"

    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/nodeinfo
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /index.php/.well-known/nodeinfo
            statusCode: 301
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Referrer-Policy
                value: "no-referrer, strict-origin-when-cross-origin"
              - name: Strict-Transport-Security
                value: "max-age=63072000; includeSubDomains"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-Frame-Options
                value: "DENY"
              - name: X-XSS-Protection
                value: "1; mode=block"
              - name: Permissions-Policy
                value: "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"

    - matches:
        - path:
            type: Exact
            value: /.well-known/host-meta
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /public.php?service=host-meta
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Referrer-Policy
                value: "no-referrer, strict-origin-when-cross-origin"
              - name: Strict-Transport-Security
                value: "max-age=63072000; includeSubDomains"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-Frame-Options
                value: "DENY"
              - name: X-XSS-Protection
                value: "1; mode=block"
              - name: Permissions-Policy
                value: "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"

    # Redirect rules
    - matches:
        - path:
            type: Exact
            value: /.well-known/carddav
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /remote.php/dav
            statusCode: 301
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Referrer-Policy
                value: "no-referrer, strict-origin-when-cross-origin"
              - name: Strict-Transport-Security
                value: "max-age=63072000; includeSubDomains"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-Frame-Options
                value: "DENY"
              - name: X-XSS-Protection
                value: "1; mode=block"
              - name: Permissions-Policy
                value: "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"

    - matches:
        - path:
            type: Exact
            value: /.well-known/caldav
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /remote.php/dav
            statusCode: 301
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Referrer-Policy
                value: "no-referrer, strict-origin-when-cross-origin"
              - name: Strict-Transport-Security
                value: "max-age=63072000; includeSubDomains"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-Frame-Options
                value: "DENY"
              - name: X-XSS-Protection
                value: "1; mode=block"
              - name: Permissions-Policy
                value: "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"
