nextcloud:
  host: nextcloud.kvlk.hu
  existingSecret:
    enabled: true
    secretName: nextcloud
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
  configs:
    custom.config.php: |-
      <?php
      $CONFIG = array (
        'overwritehost' => 'nextcloud.kvlk.hu',
        'overwriteprotocol' => 'https',
        'trusted_proxies' => array('127.0.0.1', '10.43.0.0/16'),
        'default_phone_region' => 'hu',
        'maintenance_window_start' => 1,
        "loglevel" => 3,
        "log_type" => "file",
        "logfile" => "nextcloud.log"
      );

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: pooler.postgresql.svc
  existingSecret:
    enabled: true
    secretName: nextcloud-db
    usernameKey: db-username
    passwordKey: db-password

redis:
  enabled: true
  existingSecret: "nextcloud-redis"
  existingSecretPasswordKey: "redis-password"
  architecture: standalone

global:
  storageClass: local-path

cronjob:
  enabled: true

persistence:
  enabled: true
  existingClaim: pvc-nextcloud
  size: 30Gi
