apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rustfs
resources:
  - secrets.yaml
  - rustfs.yaml
  - route.yaml
  - networkpolicy.yaml

configMapGenerator:
  - name: rustfs-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
