---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rustfs-user
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgAL7wHuUM4a//5XC91qWcTHeVSZ53Gxd2/IFmsjRRk3245MeFbG7HD6lhU1KrkD0Avx9lDwy91lZk9iQqvrogx1zdPyBmLvlriyfaWfI2Uv6S51WbD5lUZa9w/bkk4yTf1oRdk/Falg2pJrv9AF4TQKBfw4N3HT39hH7Zma6KQ1Yo39JVHCVcO4X5DtedXcAHpSLf2zo1rmQoogQX65k1euJO6RoqhwKxmTWz0QoWYx/nBm5oFDMxMfEu3rY5rkz+Ma5qHLWubxb75Kum0ZA6nIu5alPqC8yEI5+LCzig5M5qNha/hx3+1EOKvNQA6HnwDo4HnLvaIx2i9hwkWqlWQH1IUVm4nykconu+2CAigSVcTeaHY8eIow8SoFVeFEHkjuu/JlCFPpZWVRnLUwBBYTguCT3MLrY7VdsLjDSaHp35/3kFSTbbs3TUa47jZEQet2YLCaXAdb+hi1nBBT01gLThU75/Dwzp8RdQqjnHGMydcDuB9qonGFzAlVDzzHLdGenILpo5brRUjKgEngIL+/31zekM8K9O2Xg1M1UKsdtPa63OZ63mVFwQ2pHGgJN+cP732J9PF3KWwgzrAmclE7VYe8lBdCSlO3pciPBNPgh47MaM7Yfru1PXWZjkU9CudcWlTvGYF6sBOGjJShNozCcv1YKIU0xCiwM/9UIko1EpaLgyTdYNRtzdQ/AKvvFQ4HAniLfNWpNLLG
    RUSTFS_SECRET_KEY: AgCMlNorAQQ+CT1pHz8JL9XbOBGXueHJ40WMp9lQGNTUeHLUnwLudT2hHkC4QcXUjdjLWn+qmhpsI+RcLi8sJnWS3Q8qNlOR4YvTO4IOo+drPEB1gagqdgwu+jy8C6btcO6eH2DfaVzZE+WL8CVaJ1fRZCL2vSn7Myh5T3me51gaOYUqYTWBxfYZzQI82T3RqHq7wEtPe8CMUH4RWCNQxZmROHQCIyr0LvH2MiQSLE/JOM8h/tI4/5yjtrdbf4tejlxGzrmrjaKUvsqpQwnU8Un1Am/U8AtZPVdXZLyLYQQyIo8gDb+bE7liB6wH5FfTjvxpa6xZDe1QjjalBfAKR+wvD4RnKOgiGt9/VongrCtHZ37lKbp2M8pNFABhlonoAXg5L89hK9y2vu7S1bo28m3f67qr7eV5Y928jrXHLtadGxmPoIH6Z8jfvzuS1SQp2Fg52eJGGepFC0v1CTALqFI+NElCyGDp/LEYSCnMBfY/vl4yoocpW2rOXszuoK7orlVZoe1j88Q9xzf+o4/Ekj5FPK3q36TYPrRx3zHGnBK31iCvNP5HNxMMKGemob+GDZYLy4vLb/id7BMrATPgEtWAJcCJp/mMoNEUGV0WfuY5choIhDH1nU059kXp2iaWOd0BaW6ICbEB3yyICTD0QxMAfdnensT8sArKDYrvnQ6HQpfKg8azFC13GJAtHthqs7QRKcltHGt6gcIiYBBMDly3tuuVWw==
  template:
    metadata:
      creationTimestamp: null
      name: rustfs-user
      namespace: rustfs
    type: Opaque
