---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rustfs-user
  namespace: rustfs
spec:
  encryptedData:
    access_key: AgAdDDjVsh1m7vV2TCWpb176ZtyJ7RVi6np53JJZNTWQIqCnef8kbxCKFXQkm9xpdUwIHRmpStJY2ffYsVp4+cFTP8129WPPV+rB2RaT0RsA2CFX8aWF0gpyt5mlzYRCuQmvYHl/YoEeguMzY+3NqOu2aT9iSUWN0k4gY3YX16sHSmzzD4exPutqRE8LWHBasaT+EWLtug0ug63Zne/SZ19OXqCApE99xyrwti4SQXCt1kN1FyadQ83dfMQAjgOAEtGO41aFjxsSRwawmVQi8ZDjstRtprgJ4QwG1V7tNPlNbvfAAsl2xAxnRNRD9t5AweaFwc+5Z1HJMB2pyU1Hvi0ZG+vx1uBEJtcoDaraGhGcnYEoAE4Wl3ulhEMnJubNYmOyVE8VwaRuIw5D4ZM2g2kS3Aku0rBCIsBDrEpc4667I8OuQJvvwqKQU8+bxALFaqRGOFnzLPoQ1AhAXY8SP9Xg0RESfvw4QsojaayAI7UGopS5o5WsAzodq0ktninv47HmGaz0Pync76c2R97R1DxlbL8cK/EkYpiyRHeY3frQIZ/iylcsEiLuXLOuNTcYqUJMX7IzYIJ4g2oq2E/61xbIBUHiEJpB04mrFRSkcyjcZx326g4KhS8Hk4uowjlLIBrXfrTQF1a2KKcRgWPvqFpqAn5UfAqUS6dDPsAwmon3LYikLHBROas0nm1Dd4RbzFIoyhg2yAiQai+a
    secret_key: AgCJwUmoTyFxWgAtQw5Aeo1tIWwwkKz/uXqTzrvKX8ClMU2uKYlNJI9FI9R3wFsocX+5sxVxZzo7RKly8dD5eF76t4xNmodxlY3Ux1Y+3xLA/dUbfbmQit5RqGX8caGlahsFvJg4vPuWU35UjIH0+8WmHw/DcbkOdnPMvYtRmDD35L5AQT6qA2nyF6upWy01t+dU7EvAOu92MKKmLFb0pIBWBFeprtmR9fC17hJ4K7IDTcVWxjRuXgaJXMESiCKbIh229lL58AbxsFLfawi+zD+Afgg30zYQNbrcFMo7D5Sf4f9U47GYURhF1OE7T/Ucs0e1XBIknODYSMSVh01/iW4a/pcneI8a4AUP+jGAYPzwo0UTbH3BNbbOoT9qxrYlLo9yYytCh4GCXySnyha6wl5s0aGkC+9kEUCREOE4Rme5EAR2fjLBmeCWV2tmW9LKe1iuRmO5NCWGLY/Q7iB66wqWnMP1csbQoZykP5zI8qCENm9eLGbfTsixbQyNTsSBUIWRhEF8Hzce+LqxA05lRoDPM4bRKeZle6abYLbm+fH/JpKaCLsV0k44JXmpmNfubggLO8Ic9JYpos8CdpV4cMleolu2Yk8qH7apmpLxvjJfz8G+LsiEhszYufwy+qZS/dzvddpl5q+4aGKGpnxqSv9IM6j2KuPGFnVP3tA9yXQdTy7gYU1p0ps+7ybxPhKpOSfANXSf2GZ8uuFC8JuGXnVkBEHl6A==
  template:
    metadata:
      creationTimestamp: null
      name: rustfs-user
      namespace: rustfs
    type: Opaque
