mode:
  standalone:
    enabled: true
  distributed:
    enabled: false
replicCaCount: 1
ingress:
  enabled: false
config:
  rustfs:
    domains: "rustfs.kvlk.local"
secret:
  existingSecret: rustfs-user
