mode:
  standalone:
    enabled: true
  distributed:
    enabled: false
replicaCount: 1
ingress:
  enabled: false
config:
  rustfs:
    domains: "rustfs.kvlk.local:8443,rustfs.kvlk.hu"
secret:
  existingSecret: rustfs-user
enableServiceLinks: true
