mode:
  standalone:
    enabled: false
  distributed:
    enabled: true
replicaCount: 4
affinity:
  podAntiAffinity:
    enabled: false
ingress:
  enabled: false
config:
  rustfs:
    domains: "rustfs.kvlk.local:8443,rustfs.kvlk.hu"
secret:
  existingSecret: rustfs-user
enableServiceLinks: true
