---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: musicbot-env
  namespace: musicbot
spec:
  encryptedData:
    TOKEN: AgAB22nqnOs62di8ZngDAUDsY8krcPuW9B+rGn9rWskx0cRaU8tjPI77FLmmt9FwKZCFWrS9K66EmJG6lkyFbsMOzkn550DlCPdE6gsHefXb1PNRJv+ZdgFk6v29QHIm9MS2F30xWjYGdu5ZQYorV2m+InWVfzkFcDmFG5U91xeWDDmbJP4IskfqQzlUCaGFgSNSnOfnc3jV9wulgMy+lDTQCjm0gIaMPgz07znGBs5BoMPMa0n9Gvk+jDrE+k8eRaDqAn8Crcr2IfbESCQXzpYJbzegD/h0KDZbqe1QFZrJe+hfROmpfUiPSWuYagkm1onWbhsVjltAn4ndO6R1s1D5ncSCngu8+TCzQ76gUczenSCvl9XC38NhvCmaSdtOLnMaMyV86IKHHeZkorEOn2aegTKvb5e/q8oInejLhUKbe+nYOAcNKBV6HS4hNEFy7m+TBfJgEIt9yn0Lr1mWZgGrqQYrXIXJo3VZXRB6d8HmrlUvfcrNLpImyNTpS/HvyF1gnt1uLIwgMR7qehnHjzgZJQBnzsOFu8jDSLg5x0gfmzlxIVRheUGmgG3WhiLw9wlXDK9HmdPMMYtSZr+gcN0cVvzFdfjXh+KOJyfAtnwEmfPvz+Ap211DSbr4iUep+AAxp5taZbYlR09YW0t0abLpLu9H919dK+oqldRy/csNqqrWvnl4NxTeGUPMLxsPL87W2+lzXn0WvlEP/ZaMPyLJDtoeILGbapW6DfgspHbg/agME77ai/J2UPUViy7oXXgInFvfAy3gheZOSYYeGzJv2bImZM4S
  template:
    metadata:
      creationTimestamp: null
      name: musicbot-env
      namespace: musicbot
